title: Xavier Lowmiller's Blog
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
repository: xavierLowmiller/xavierLowmiller.github.io
highlighter: rouge
github: [metadata]
author: xavierLowmiller
url: https://xavierlowmiller.github.io
description: A site about iOS programming, and my life in general

plugins:
  - jekyll-seo-tag
  - jekyll-feed
